/* Project data sourced from the GitHub REST API on 2026-09-17.
 * Star counts, language rollups, contributors and homepages are the live
 * values returned by api.github.com — not placeholders. */

export const PROFILE = {
  name: "Mir Kashif",
  alias: "Loop Lord",
  handle: "mirkashi",
  role: "Full-Stack Developer · Digital Architect",
  location: "Islamabad, Pakistan",
  bio: "Code Alchemist 🪄 | Loop Lord | MERN ✦ Full Stack ✦ Digital Architect",
  github: "https://github.com/mirkashi",
  portfolio: "https://looplord.vercel.app/",
  linkedin: "https://www.linkedin.com/in/mir-kashif-28987428b",
  twitter: "https://x.com/LoopLord10",
  email: "mirkashi111@gmail.com",
  avatar: "https://avatars.githubusercontent.com/u/138784444?v=4",
  followers: 46,
  following: 16,
  publicRepos: 18,
  since: "2023",
};

export const ORG = {
  name: "BITSANDBYTESDUDE",
  handle: "BITSANDBYTESDUDE",
  tagline: "Software company · innovative digital solutions",
  location: "United States of America",
  site: "https://bitsandbytesdude.vercel.app/",
  twitter: "https://x.com/bitsandbytes_10",
  github: "https://github.com/BITSANDBYTESDUDE",
  avatar: "https://avatars.githubusercontent.com/u/240355952?v=4",
  publicRepos: 10,
  followers: 3,
};

/* Remote screenshots live on GitHub's asset CDN (they resolve in the browser).
 * `cover` is the local fallback shipped with this site, so the grid always
 * looks complete even with no network access. */
export const MIREXAMPLES = [
  {
    id: "loop-lord",
    name: "Loop Lord",
    kicker: "Flagship portfolio",
    desc: "Personal portfolio site — animated sections, project showcase, testimonials and a direct contact experience. Built as HTML, CSS and vanilla JS.",
    tech: ["HTML5", "CSS3", "JavaScript", "Netlify"],
    stars: 4,
    cat: "web",
    repo: "https://github.com/mirkashi/Loop-Lord",
    demo: "https://looplord.netlify.app/",
    cover: "assets/img/looplord.jpg",
    shots: ["https://github.com/user-attachments/assets/8a011652-514d-4c8a-b04a-1f69853d9d9a"],
    langs: "HTML 50% · CSS 40% · JS 8%",
    featured: true,
  },
  {
    id: "looplord-next",
    name: "Looplord",
    kicker: "Portfolio rebuild",
    desc: "Second-generation portfolio exploring a component-driven layout, refined typography and smoother section transitions.",
    tech: ["CSS", "HTML", "JavaScript", "Node.js"],
    stars: 0,
    cat: "web",
    repo: "https://github.com/mirkashi/Looplord",
    demo: null,
    cover: "assets/img/looplord.jpg",
    shots: [],
    langs: "CSS 46% · HTML 29% · JS 23%",
  },
  {
    id: "barber-master",
    name: "Barber Master",
    kicker: "Local business site",
    desc: "Responsive barbershop website built around services, pricing, gallery and a short path to booking an appointment.",
    tech: ["HTML", "CSS", "JavaScript", "GitHub Pages"],
    stars: 4,
    cat: "web",
    repo: "https://github.com/mirkashi/Barber-master",
    demo: "https://mirkashi.github.io/Barber-master/",
    cover: "assets/img/barber-hero.jpg",
    shots: ["https://github.com/mirkashi/Barber-master/assets/138784444/adb19f14-4b1f-46aa-baaf-fd8635853068"],
    langs: "HTML 55% · CSS 40% · JS 3%",
    featured: true,
  },
  {
    id: "food-restaurant",
    name: "Food Restaurant",
    kicker: "Menu-driven landing",
    desc: "Restaurant website with a menu-first layout, special-dish banners and a location section — all hand-built without a framework.",
    tech: ["HTML", "CSS", "JavaScript"],
    stars: 1,
    cat: "web",
    repo: "https://github.com/mirkashi/Food-Restaurant",
    demo: "https://mirkashi.github.io/Food-Restaurant/",
    cover: "assets/img/food.jpg",
    shots: ["https://github.com/mirkashi/Food-Restaurant/assets/138784444/990039db-5d4b-4684-971c-f151eea0883a"],
    langs: "HTML 48% · CSS 47% · JS 4%",
  },
  {
    id: "gym-website",
    name: "Gym Website",
    kicker: "Fitness landing",
    desc: "Gym website with structured sections for memberships, classes, trainers and calls to action — now migrated to TypeScript.",
    tech: ["TypeScript", "CSS", "GitHub Pages"],
    stars: 1,
    cat: "web",
    repo: "https://github.com/mirkashi/Gym-website",
    demo: "https://mirkashi.github.io/Gym-website/",
    cover: "assets/img/cover-gym.svg",
    shots: [],
    langs: "TypeScript 86% · JS 13%",
  },
  {
    id: "aquagrow",
    name: "AquaGrow",
    kicker: "Final-year e-commerce",
    desc: "Aquaponics storefront built as a final-year project: product discovery, cart flow and a clean product-first catalogue layout.",
    tech: ["JavaScript", "HTML", "CSS"],
    stars: 1,
    cat: "web",
    repo: "https://github.com/mirkashi/AquaGrow",
    demo: null,
    cover: "assets/img/aquagrow.jpg",
    shots: [],
    langs: "JS 47% · HTML 27% · CSS 25%",
  },
  {
    id: "paksky-wings",
    name: "Paksky Wings",
    kicker: "Travel experience",
    desc: "Travel website built with only HTML and CSS — destination galleries, packages and a journey-first browsing flow.",
    tech: ["HTML", "CSS"],
    stars: 1,
    cat: "web",
    repo: "https://github.com/mirkashi/Paksky-Wings",
    demo: "https://mirkashi.github.io/Paksky-Wings/",
    cover: "assets/img/paksky.jpg",
    shots: ["https://github.com/user-attachments/assets/665f82f2-867d-4305-9513-09b795b22740"],
    langs: "HTML 50% · CSS 44% · JS 5%",
  },
  {
    id: "ai-chatbot",
    name: "AI Chatbot",
    kicker: "LLM experiment",
    desc: "Conversational assistant built with LangChain and OpenAI's gpt-4o-mini, served through a Streamlit interface. Notebook-driven research.",
    tech: ["Python", "LangChain", "OpenAI", "Streamlit"],
    stars: 2,
    cat: "ai",
    repo: "https://github.com/mirkashi/AI-Chatbot-Using-LLM-Public",
    demo: null,
    cover: "assets/img/cover-ai-chat.svg",
    shots: [],
    langs: "Jupyter Notebook 100%",
  },
  {
    id: "headphone-web",
    name: "Headphone Web",
    kicker: "Product landing",
    desc: "Responsive headphone landing page with scroll sections, product specs and a discount block — styled in SCSS.",
    tech: ["SCSS", "HTML", "JavaScript"],
    stars: 0,
    cat: "web",
    repo: "https://github.com/mirkashi/Headphone-web",
    demo: null,
    cover: "assets/img/headphone-web.jpg",
    shots: [],
    langs: "SCSS 35% · HTML 29% · CSS 27%",
  },
  {
    id: "js-course",
    name: "JavaScript Course",
    kicker: "123 commits of practice",
    desc: "Six-month JavaScript track: data types, conversions, objects, JSON, strings and DOM practice — logged commit by commit.",
    tech: ["JavaScript", "DOM", "JSON"],
    stars: 4,
    cat: "learn",
    repo: "https://github.com/mirkashi/JavaScript-course",
    demo: null,
    cover: "assets/img/cover-js-course.svg",
    shots: [],
    langs: "JavaScript 100%",
  },
  {
    id: "cursor-design",
    name: "Cursor Design",
    kicker: "Micro-interaction lab",
    desc: "Small experiments with custom cursors, magnetic hover states and playful frontend motion details.",
    tech: ["CSS", "JavaScript", "UI motion"],
    stars: 0,
    cat: "lab",
    repo: "https://github.com/mirkashi/cursor-Design",
    demo: null,
    cover: "assets/img/cover-cursor.svg",
    shots: [],
    langs: "HTML / CSS / JS",
  },
  {
    id: "3d-flip-card",
    name: "3D Flip Card",
    kicker: "CSS 3D transform",
    desc: "Profile card built on CSS 3D transforms — perspective, backface-visibility and a spring-like flip on hover.",
    tech: ["CSS 3D", "HTML", "JavaScript"],
    stars: 0,
    cat: "lab",
    repo: "https://github.com/mirkashi/3d-Flip-card",
    demo: "https://mirprofilecard.netlify.app",
    cover: "assets/img/flipcard.jpg",
    shots: [],
    langs: "CSS 63% · HTML 36%",
  },
  {
    id: "weather-app",
    name: "Weather App",
    kicker: "API-driven widget",
    desc: "Weather lookup with live API data, condition-specific artwork and error states for unknown cities.",
    tech: ["JavaScript", "CSS", "REST API"],
    stars: 1,
    cat: "web",
    repo: "https://github.com/mirkashi/weather-app",
    demo: null,
    cover: "assets/img/weather.jpg",
    shots: ["https://github.com/mirkashi/weather-app/assets/138784444/c2544fbc-9f42-43d4-bb97-951d6f459ed3"],
    langs: "CSS 37% · JS 32% · HTML 30%",
  },
  {
    id: "shoe-store",
    name: "Shoe Store",
    kicker: "Landing page",
    desc: "Sneaker store landing page with a bold hero, product row and animated call-to-action.",
    tech: ["HTML", "CSS", "JavaScript"],
    stars: 1,
    cat: "web",
    repo: "https://github.com/mirkashi/shoe-store",
    demo: null,
    cover: "assets/img/shoe.jpg",
    shots: [],
    langs: "CSS 56% · HTML 43%",
  },
  {
    id: "profile-card",
    name: "Profile Card",
    kicker: "UI component",
    desc: "Profile card component with social icon links and a compact work intro — reusable across portfolio experiments.",
    tech: ["CSS", "HTML"],
    stars: 1,
    cat: "lab",
    repo: "https://github.com/mirkashi/Profile-card.",
    demo: "https://mirkashi.github.io/Profile-card./",
    cover: "assets/img/cover-cursor.svg",
    shots: [],
    langs: "CSS 72% · HTML 27%",
  },
  {
    id: "c-program",
    name: "C++ Programs",
    kicker: "67 commits",
    desc: "C++ practice repository covering fundamentals, control flow and data structures.",
    tech: ["C++"],
    stars: 1,
    cat: "learn",
    repo: "https://github.com/mirkashi/c-Program",
    demo: null,
    cover: "assets/img/cover-cprog.svg",
    shots: [],
    langs: "C++ 100%",
  },
];

export const BBDPROJECTS = [
  {
    id: "actiondoc-ai",
    name: "ActionDoc AI",
    kicker: "Document intelligence platform",
    desc: "Upload a business document and the AI extracts the actions buried inside it — tasks, owners, deadlines — as suggestions a human approves. PDF/DOCX/TXT/Markdown in, tracked work out.",
    tech: ["TypeScript", "Next.js", "pdf.js", "Zod", "SHA-256 dedupe"],
    stars: 0,
    cat: "ai",
    repo: "https://github.com/BITSANDBYTESDUDE/ActionDoc-AI",
    demo: null,
    cover: "assets/img/cover-actiondoc-ai.svg",
    shots: [],
    langs: "TypeScript 99%",
    updated: "Sep 2026",
    featured: true,
  },
  {
    id: "sitepulse",
    name: "SitePulse",
    kicker: "Website health audit engine",
    desc: "Point it at any public URL and get an evidence-based audit: performance, SEO, accessibility, security, mobile, content, images, links and conversion. Real crawl, reproducible scores, PDF/JSON/CSV exports.",
    tech: ["Next.js 14", "Express", "TypeScript", "Playwright", "SSE", "MongoDB"],
    stars: 0,
    cat: "tool",
    repo: "https://github.com/BITSANDBYTESDUDE/Website-Health-Audit",
    demo: "https://sitepulse-rho.vercel.app",
    cover: "assets/img/cover-sitepulse.svg",
    shots: [],
    langs: "TypeScript 99%",
    updated: "Sep 2026",
    featured: true,
  },
  {
    id: "pdf-contact",
    name: "PDF Contact Extractor",
    kicker: "Offline OCR pipeline",
    desc: "Drag in text or scanned PDFs, review the names and phone numbers it finds, resolve duplicates, export real .xlsx or CSV. Fully offline OCR — no account, no paid API, no external AI.",
    tech: ["Next.js 16", "React 19", "Express 5", "Tesseract.js", "libphonenumber-js", "SheetJS"],
    stars: 0,
    cat: "tool",
    repo: "https://github.com/BITSANDBYTESDUDE/PDF-Contact-Extractor",
    demo: "https://pdf-contact-extractor-gamma.vercel.app",
    cover: "assets/img/cover-pdf-contact.svg",
    shots: [],
    langs: "TypeScript 70% · CSS 28%",
    updated: "Sep 2026",
    featured: true,
  },
  {
    id: "smart-profits",
    name: "Smart Profits",
    kicker: "Business finance SaaS",
    desc: "Finance workspace with registration, dashboard, an advisor flow and a scenario simulator — every figure computed server-side rather than mocked in the UI.",
    tech: ["TypeScript", "Next.js", "Vercel"],
    stars: 0,
    cat: "saas",
    repo: "https://github.com/BITSANDBYTESDUDE/Smart-Profits",
    demo: "https://smart-profits-ruddy.vercel.app",
    cover: "assets/img/smart-profits.jpg",
    shots: [],
    langs: "TypeScript 99%",
    updated: "Sep 2026",
    featured: true,
    gallery: ["assets/img/smart-profits.jpg", "assets/img/smart-profits-b.jpg"],
  },
  {
    id: "9t-angle-ops",
    name: "9T-Angle Operations",
    kicker: "Agency management platform",
    desc: "Employee tasks, daily/weekly/monthly targets, attendance, eBay operations and a weighted performance engine. JWT sessions, RBAC, scheduler-driven alerts, CSV/XLSX/PDF exports.",
    tech: ["Next.js 16", "React 19", "Express 5", "MongoDB", "Mongoose", "Zod", "Recharts"],
    stars: 1,
    cat: "saas",
    repo: "https://github.com/BITSANDBYTESDUDE/9T-Angle-Management",
    demo: null,
    cover: "assets/img/cover-9t-angle.svg",
    shots: [],
    langs: "TypeScript 99%",
    updated: "Aug 2026",
    featured: true,
  },
  {
    id: "report-hub",
    name: "ReportHub",
    kicker: "Skeuomorphic MERN system",
    desc: "Weekly work-report system with a fully skeuomorphic interface — leather, brushed metal, paper and glass. Employee and admin panels, JWT auth, drafts, approvals and analytics.",
    tech: ["MongoDB", "Express", "React", "Node.js", "JWT"],
    stars: 0,
    cat: "saas",
    repo: "https://github.com/BITSANDBYTESDUDE/report-hub",
    demo: "https://report-hub-ivory.vercel.app",
    cover: "assets/img/cover-report-hub.svg",
    shots: [],
    langs: "JavaScript 83% · CSS 16%",
    updated: "Jul 2026",
  },
  {
    id: "solr-blog",
    name: "Solar Expert",
    kicker: "MERN content platform",
    desc: "Full-stack MERN blog and content platform for solar expertise — production-ready structure with article management and a public reading experience.",
    tech: ["MongoDB", "Express", "React", "Node.js"],
    stars: 0,
    cat: "web",
    repo: "https://github.com/BITSANDBYTESDUDE/solr-blog",
    demo: null,
    cover: "assets/img/cover-solr-blog.svg",
    shots: [],
    langs: "JavaScript 65% · CSS 33%",
    updated: "Jan 2026",
  },
  {
    id: "smartorder",
    name: "SmartOrderReader",
    kicker: "Invoice OCR to CSV",
    desc: "Python tool that OCRs images of invoices, order confirmations and receipts, pulls the order number and date from each, and writes a clean CSV ready for Excel.",
    tech: ["Python", "OCR", "CSV"],
    stars: 0,
    cat: "tool",
    repo: "https://github.com/BITSANDBYTESDUDE/SmartOrderReader",
    demo: null,
    cover: "assets/img/cover-smartorder.svg",
    shots: [],
    langs: "Python 100%",
    updated: "Dec 2025",
  },
  {
    id: "9t-angle-form",
    name: "9T-Angle Internship Form",
    kicker: "Static intake page",
    desc: "Single-page internship application form for the 9T-Angle hiring flow — pure HTML, no dependencies.",
    tech: ["HTML"],
    stars: 0,
    cat: "web",
    repo: "https://github.com/BITSANDBYTESDUDE/9t-angle",
    demo: null,
    cover: "assets/img/cover-9t-angle.svg",
    shots: [],
    langs: "HTML 100%",
    updated: "Aug 2026",
  },
];

/* Verified rollups across both accounts (api.github.com, 2026-09-17).
 * Star totals count every public repo, including the two not shown as cards
 * (`mirkashi` = 2 stars, `skills-introduction-to-git` = 0). */
export const STATS = {
  mirRepos: 18,
  bbdRepos: 10,
  totalRepos: 28,
  mirStars: 24,
  bbdStars: 1,
  totalStars: 25,
  followers: 46,
  liveSites: 12,
  leadContributorOn: 9, // of 10 BITSANDBYTESDUDE repos, mirkashi is a listed contributor
};
